### PR TITLE
Support launching a specific page via env variable / Add desktop entries

### PR DESCRIPTION
**Pull request by mmstick**
Requires https://github.com/pop-os/gnome-control-center/pull/187 to be installed

### CODE REVIEW

**Comment by jacobgkau** [comment]
Testing this together with https://github.com/pop-os/gnome-control-center/pull/187, the .desktop files don't seem to be getting installed.

Screenshot from 2021-07-08 13-09-33

I don't see the four new .desktop files in `/usr/share/applications/`, `/usr/local/share/applications/` doesn't exist, and the four .desktop files are not listed in `dpkg -L libpop-desktop-widget`.

The environment variables do work for launching the control center to specific pages using the terminal.

**Comment by ids1024** [comment]
I guess the `.desktop` files need to be added to `libpop-desktop-widget.install`.

**Review by jackpot51 — APPROVED** [review]

**Review by jackpot51 — CHANGES_REQUESTED** [review]
@ids1024 is probably right, the .desktop files have no matching package that installs them

**Comment by jacobgkau** [comment]
The .desktop files are now being installed.

The issue I mentioned in [this comment](https://github.com/pop-os/gnome-control-center/pull/187#issuecomment-876721122) also seems to apply for the .desktop files and for launching from the terminal; if I focus to any non-Desktop page in Settings, then close it, I'm always brought to Desktop -> General, even if I select something else (like Dock or Appearance.) If I'm focused anywhere in the Desktop section, then I'm brought directly to the correct section, like Desktop -> Dock or Desktop -> Appearance.

**Review by leviport — APPROVED** [review]
This is looking good. The only oddity I'm noticing is that if I search "background" or "wallpaper", I still only get the "Desktop" entry, and it doesn't always show up as the first item when searching "background". However, selecting the "Desktop" entry still takes me to the Backgrounds section of GCC, so I think that might be fine. "Desktop" and "Background" have an obvious connection in my mind, so I think that's still plenty discoverable. Besides, I would assume most users looking to change their wallpaper probably find that page by right clicking on the desktop and clicking "change background" anyway.

Screenshot from 2021-07-09 10-19-22
Screenshot from 2021-07-09 10-19-29


Edit: Now I'm seeing the bug Jacob is seeing. I missed it earlier.

**Comment by mmstick** [comment]
Will look into the timing issue with the launcher getting set to General
The Desktop item is coming from our GCC package, so I'll update the descriptions (or remove that file from GCC?)

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
