### PR TITLE
Behaviour to handle when the user disables super key behaviour in COSMIC

### PR DESCRIPTION
**Pull request by jmaargh**
Following discussion and design from https://github.com/pop-os/cosmic/pull/183

image

### CODE REVIEW

**Comment by jacobgkau** [comment]
Failed to build on the build server with this message:
```
cargo build --release --frozen
error: failed to get `glib` as a dependency of package `ffi v0.1.2 (/<<PKGBUILDDIR>>/ffi)`

Caused by:
  attempting to make an HTTP request, but --frozen was specified
```
I don't think this is related to the changes being made, we probably need a fix like [this](https://github.com/pop-os/upgrade/pull/207/commits/b40cba8cdc6f22bf655136d9c9b7f69d856c48a3) or [this](https://github.com/pop-os/system76-power/blob/006230d3bd4098cbfa3e7658fc3ebe394cbe273b/Makefile#L12) for desktop-widget. I'm assuming the first one is better.

**Comment by ids1024** [comment]
Currently the code here crashes if the installed version of Cosmic doesn't have the gsettings key. It's probably better to add a test against `settings.get_property_settings_schema().map_or(false, |x| x.has_key("disable-overlay-key"))` (like some other existing code) to disable this logic when the gsettings key isn't found.

**Comment by jmaargh** [comment]
@ids1024 nice catch, fixed

**Comment by jacobgkau** [comment]
This increases the minimum width of the widgets on the Desktop -> General settings page, only when the override has been disabled. This doesn't change the width that libhandy collapses the columns, but instead adds horizontal scrolling on the page when it's too small:

Screenshot from 2021-08-12 12-58-07

It would be better if the text wrapped so this didn't happen. Would it be feasible to make the label text wrap? Aside from that nitpick, testing is looking great on this.

**Comment by jacobgkau** [comment]
I figured out the text wrapping and pushed a commit to fix that.

Screenshot from 2021-08-12 13-12-11

**Review by jacobgkau — APPROVED** [review]
Tested with https://github.com/pop-os/cosmic/pull/183.

**Review by ids1024 — APPROVED** [review]

**Pull request merged**
