### PR TITLE
i18n(tr): Add Turkish translation

### PR DESCRIPTION
**Pull request by oguzkarayemis**
Added Turkish translation of Pop Desktop Settings Widget.

### CODE REVIEW

**Comment by oguzkarayemis** [comment]
Ok I surely couldn't use this github thing. Sorry for mess, but translation isn't mess, I'm confident about that.

**Comment by oguzkarayemis** [comment]
Also I couldn't find any lines for translate these expressions. If you want to add their translations, here they are:
Desktop: Masaüstü
Desktop Options: Masaüstü Seçenekleri
Ekran Görüntüsü - 2022-06-10 19-13-54

**Review by jackpot51 — APPROVED** [review]

**Comment by XV-02** [comment]
The translation looks good! Thank you. There is one issue, but this is otherwise looking good:
The line 
`mountdock-mounted-drives = Bağlanmış Aygıtları Göster` 
should be 
`dock-mounted-drives = Bağlanmış Aygıtları Göster`

**Comment by oguzkarayemis** [comment]
> The translation looks good! Thank you. There is one issue, but this is otherwise looking good: The line `mountdock-mounted-drives = Bağlanmış Aygıtları Göster` should be `dock-mounted-drives = Bağlanmış Aygıtları Göster`

Sorry for this typo, while testing I'm trying to understand what is wrong there just now. Should I correct this one? If so, how?

And also, you're welcome, I love Pop!_OS and am happy to contribute it.

**Comment by XV-02** [comment]
The only change needed would be to change `moundock-mounted-drives` to `dock-mounted-drives`
looks like it is only a typo, but it stop that piece of translation showing correctly in the settings.

**Comment by oguzkarayemis** [comment]
I did I think, didn't I? Sorry for my lack of experience regarding Github. Today it's the first time ever I tried to do fork, pull request etc...

**Review by XV-02 — APPROVED** [review]
It looks good! Thank you for helping to translate Pop-OS for a wider audience. We appreciate your time and effort in making Linux more accessible!

**Pull request merged**
