### PR TITLE
i18n(sr): Add Serbian (Latin) translation

### PR DESCRIPTION
**Pull request by AAnzel**

### CODE REVIEW

**Comment by jacobgkau** [comment]
Thank you for the translation! The file you've added looks correct, but this does not seem to be working:

Снимак екрана из „2021-07-15 10-11-18“
Snimak ekrana iz „2021-07-15 10-12-38“

@mmstick Does desktop-widget need a fix similar to https://github.com/pop-os/upgrade/pull/175 to get translations working?

**Comment by AAnzel** [comment]
You're welcome!

**Comment by mmstick** [comment]
It does need a similar fix

**Review by jacobgkau — APPROVED** [review]
This branch is now out of date, but the translation displays properly after https://github.com/pop-os/desktop-widget/pull/39.

**Pull request merged**
