### PR TITLE
Empty sensors fix

### PR DESCRIPTION
**Pull request by ahoneybun**
Currently the logs will create an empty sensors file on non-System76 hardware. This is because the system76-driver pulls in lm-sensors. This PR does the following:

- Adds the lm-sensor dep
- Reorders the build-depends to match Debian standard
- Updates the d/compat level to 10 to fix build warnings
- Updates the d/changelog to 0.2.1

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Review by jackpot51 — APPROVED** [review]

**Comment by ahoneybun** [comment]
It looks like the latest change *does* install the `lm-sensors` package though the sensors file is still empty.

**Comment by ahoneybun** [comment]
Using `gnome-control-center support`then creating logs doesn't seem to log anything other then the logs being created. 

UPDATE: It's because I was testing in a VM. Simcha is testing on real hardware for me.

**Comment by ahoneybun** [comment]
Alright so `lm-sensors` was installed and the sensor file has data now.

**Comment by jacobgkau** [comment]
I'm confused what this has to do with desktop-widget. Would it make more sense for support-panel to depend on lm-sensors instead of desktop-widget?

**Comment by ahoneybun** [comment]
Now that I know that exists I believe I agree with you @jacobgkau . I'll make a new PR there in a bit.

**Comment by XV-02** [comment]
Action plan is to pursue this through another repo. Closing for housekeeping/organization purposes.

**Pull request closed without merging**
