### PR TITLE
Integrating GNOME Initial Setup pages

### PR DESCRIPTION
**Pull request by mmstick**

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Review by jacobgkau — APPROVED** [review]
This doesn't seem to affect the appearance or behavior of the Desktop section in Settings.

The only copy difference I see is `Dock extends to edges` instead of `Dock extends to the edges` from the mockup (and `Dock doesn't extend to edges` instead of `Dock doesn't extend to the edges`.) I'm mentioning that because I noticed it, but I actually think the former wordings read better in this case (because these aren't full sentences), so I don't think they should be changed. (cc: @maria-komarova just in case.)

**Comment by maria-komarova** [comment]
I was mulling over this wording trying to make it shorter but maybe we should opt for consistency and keep it exactly the same as on the Desktop panel. I'm not entirely sure.

**Comment by maria-komarova** [comment]
@mmstick looking at this merge request, are we ready for the visual assets to be added to the Launcher and Gestures pages in the Initial setup? At minimum we could use illustrations but I was originally thinking about using animations in the form of video files. Let me know where we are with it and I'll provide the assets.

**Comment by jacobgkau** [comment]
> I was mulling over this wording trying to make it shorter but maybe we should opt for consistency and keep it exactly the same as on the Desktop panel.

I'm not sure that would work, only because the Desktop panel currently has an `Enable Dock` setting and a separate setting for `Extend dock to the edges of the screen`, while the GIS page/mockup has one setting with three options. Unless you just mean changing GIS to `Extend dock to the edges of the screen` and `Don't extend dock to the edges of the screen`.

Like I said, the shortened version just reads more naturally without `the`, which is probably why @mmstick deviated from the mockup. `to the edges` is ambiguous without `of the screen` after it; it should either be just `to edges` for a terse phrase, or `to the edges of the screen` for a fuller phrase.

> @mmstick looking at this merge request, are we ready for the visual assets to be added to the Launcher and Gestures pages in the Initial setup?

It looks like Michael's already added the static pages that don't control any settings to https://github.com/pop-os/gnome-initial-setup/pull/70, although I haven't gotten a chance to look at it since it won't build until this PR is merged.

**Comment by maria-komarova** [comment]
Yes, I merely meant the copy. I'm fine with keeping it "Dock extends to edges" and "Dock doesn't extend to edges".

**Pull request merged**
